package com.linearity.utils.FakeInfo;

import com.linearity.utils.ExtendedRandom;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class ExpectInfo {
    public static final HashMap<Long,ExpectInfo> INSTANCES = new HashMap<>();
    public final Map<String, Object> kvMap = new HashMap<>();

    public ExpectInfo(ExtendedRandom random){
        kvMap.put("screen_brightness", random.nextInt(100));
        kvMap.put("time_12_24", random.nextBoolean()?"24":"12");
        kvMap.put("haptic_feedback_enabled", random.next0or1());
        kvMap.put("sound_effects_enabled", random.next0or1());
        kvMap.put("adb_enabled", random.next0or1());
        kvMap.put("screen_brightness_mode", random.next0or1());
        kvMap.put("airplane_mode_on","0");
        kvMap.put("enable_freeform_support", random.next0or1());
        kvMap.put("one_handed_mode_enabled", random.next0or1());
        kvMap.put("one_handed_mode_timeout",null);
        kvMap.put("swipe_bottom_to_notification_enabled", random.next0or1());
        kvMap.put("battery_estimates_last_update_time",String.valueOf(Math.min(Math.max(random.nextLong(),1717751189 + random.nextInt(1000000)),System.currentTimeMillis() - 10000)));
        kvMap.put("time_remaining_estimate_millis",random.nextBoolean()?"-1":String.valueOf(random.nextLong()));
        kvMap.put("animator_duration_scale",String.valueOf(random.nextSmallDouble(1.1)));
        kvMap.put("transition_animation_scale",String.valueOf(random.nextSmallDouble(1.1)));
        kvMap.put("taps_app_to_exit",null);
        kvMap.put("accessibility_button_targets",null);
        kvMap.put("accessibility_shortcut_target_service",null);
        kvMap.put("always_on_display_constants",null);
        kvMap.put("systemui/buffer/BroadcastDispatcherLog",null);
        kvMap.put("systemui/tag/BroadcastDispatcherLog",null);
        kvMap.put("sysui_tuner_demo_on", random.next0or1());
        kvMap.put("sysui_demo_allowed", random.next0or1());
        kvMap.put("sysui_tuner_version",String.valueOf(random.nextInt(5)));
        kvMap.put("device_provisioned","1");
        kvMap.put("doze_always_on",null);
        kvMap.put("accessibility_display_inversion_enabled",null);
        kvMap.put("zen_mode","0");
        kvMap.put("user_setup_complete","1");
        kvMap.put("qs_media_resumption",null);
        kvMap.put("qs_media_controls",null);
        kvMap.put("qs_media_recommend",null);
        kvMap.put("systemui/flags/101",null);
        kvMap.put("lockscreenSimpleUserSwitcher",null);
        kvMap.put("add_users_when_locked","0");
        kvMap.put("allow_user_switching_when_system_user_locked",null);
        kvMap.put("low_battery_sound",random.nextPackageName("/") + ".ogg");
        kvMap.put("lock_sound",random.nextPackageName("/") + ".ogg");
        kvMap.put("unlock_sound",random.nextPackageName("/") + ".ogg");
        kvMap.put("trusted_sound",random.nextPackageName("/") + ".ogg");
        kvMap.put("render_shadows_in_compositor",null);
        kvMap.put("sysui_volume_down_silent",null);
        kvMap.put("sysui_volume_up_silent",null);
        kvMap.put("rtt_calling_mode","0");
        kvMap.put("roaming_settings",null);
        kvMap.put("rtt_mode",null);
        kvMap.put("qti.settings.auto_reject0",null);
        kvMap.put("data_roaming5","0");
        kvMap.put("pdp_watchdog_poll_interval_ms",null);
        kvMap.put("data_stall_recovery_on_bad_network",null);
        kvMap.put("captive_portal_mode",null);
        kvMap.put("captive_portal_https_url",null);
        kvMap.put("captive_portal_http_url",null);
        kvMap.put("captive_portal_fallback_url",null);
        kvMap.put("wifi_on",random.next0or1());
        kvMap.put("ims_profile_override",null);
        kvMap.put("lock_screen_lock_after_timeout",null);
        kvMap.put("nr_nsa_tracking_screen_off_mode",null);
        kvMap.put("systemui/flags/201",null);
        kvMap.put("doze_quick_pickup_gesture",null);
        kvMap.put("pdp_watchdog_long_poll_interval_ms",null);
        kvMap.put("radio.data.stall.recovery.action","0");
        kvMap.put("contacts_database_wal_enabled",null);
        kvMap.put("carrier_app_whitelist",random.nextRandomHexUpper(64)+":com.google.android.apps.tycho");
        kvMap.put("notification_badging","1");
        kvMap.put("new_contact_aggregator",null);
        kvMap.put("lockscreen_sounds_enabled",random.next0or1());
        kvMap.put("multi_cb",String.valueOf(random.nextInt(3)));
        kvMap.put("nfc_payment_foreground",null);
        kvMap.put("android_id",random.nextRandomHexLower(16));
        kvMap.put("tether_offload_disabled","1");
        kvMap.put("accessibility_captioning_locale",null);
        kvMap.put("accessibility_captioning_enabled",null);
        kvMap.put("POWER_SAVE_MODE_OPEN",null);
        kvMap.put("show_ime_with_hard_keyboard",random.next0or1());
        kvMap.put("volume_key_cursor_control",null);
        kvMap.put("font_scale",String.valueOf(random.nextSmallDouble(1.1)));
        kvMap.put("high_text_contrast_enabled",null);
        kvMap.put("gb_boosting",null);
        kvMap.put("quick_reply",null);
        kvMap.put("ringtone_set",random.next0or1());
        kvMap.put("notification_sound_set",random.next0or1());
        kvMap.put("alarm_alert_set",random.next0or1());
        kvMap.put("voice_interaction_service","");
        kvMap.put("backup_local_transport_parameters",null);
        kvMap.put("enabled_accessibility_services",null);
        kvMap.put("accessibility_display_magnification_enabled","0");

        kvMap.put("download_manager_max_bytes_over_mobile",null);
        kvMap.put("download_manager_recommended_max_bytes_over_mobile",null);
        kvMap.put("google_play_store_system_component_update",null);
        kvMap.put("package_verifier_user_consent","1");
        kvMap.put("selected_search_engine_aga",null);
        kvMap.put("google_ota_automatic_download",null);
        kvMap.put("location_access_check_interval_millis",null);
        kvMap.put("location_mode",String.valueOf(random.nextInt(4)));
        kvMap.put("device_name",random.nextString(random.nextInt(10)+5));
        kvMap.put("low_power_trigger_level",random.nextInt(30) + 1);
        kvMap.put("low_power",random.next0or1());
        int tempInt = random.nextInt(574);
        kvMap.put("Phenotype_boot_count",String.valueOf(tempInt));
        kvMap.put("boot_count",String.valueOf(tempInt+1));
        kvMap.put("_boot_Phenotype_flags","");
        kvMap.put("Phenotype_flags","");
        kvMap.put("locationPackagePrefixBlacklist",null);
        kvMap.put("locationPackagePrefixWhitelist",null);
        kvMap.put("enabled_notification_listeners","");
        kvMap.put("upload_apk_enable",random.next0or1());
        kvMap.put("ota_disable_automatic_update",random.next0or1());
        kvMap.put("instant_apps_enabled",null);
        kvMap.put("migrate_backup_enabled",null);
        kvMap.put("migrate_full_data_aware_original",null);

        kvMap.put("sysui_do_not_disturb",null);
        kvMap.put("heads_up_snooze_length_ms",null);
        kvMap.put("heads_up_notifications_enabled",random.next0or1());
        kvMap.put("icon_blacklist",null);
        kvMap.put("device_demo_mode",null);
        kvMap.put("settings_provider_model",null);
        kvMap.put("systemui/flags/601",null);
        kvMap.put("systemui/buffer/DozeLog",null);
        kvMap.put("systemui/tag/DozeLog",null);
        kvMap.put("show_media_when_bypassing",null);
        kvMap.put("back_gesture_inset_scale_left",null);
        kvMap.put("back_gesture_inset_scale_right",null);
        kvMap.put("systemui/flags/203",null);
        kvMap.put("systemui/flags/700",null);
        kvMap.put("systemui/flags/701",null);
        kvMap.put("nfc_payment_default_component",null);
        kvMap.put("systemui/flags/501",null);
        kvMap.put("lockscreen_show_controls",random.next0or1());
        kvMap.put("notification_history_enabled",null);
        kvMap.put("high_priority",null);
        kvMap.put("controls_providers",null);
        kvMap.put("double_tap_to_wake",null);
        kvMap.put("doze_pulse_on_double_tap",null);
        kvMap.put("doze_tap_gesture",null);
        kvMap.put("accessibility_button_mode",String.valueOf(random.nextInt(3)));
        kvMap.put("sqlite_compatibility_wal_flags",null);
        kvMap.put("assistant","");
        kvMap.put("assist_long_press_home_enabled",null);
        kvMap.put("assist_touch_gesture_enabled",null);
        kvMap.put("tether_force_usb_functions",null);
        kvMap.put("accelerometer_rotation",String.valueOf(random.nextInt(3)));
        kvMap.put("systemui/buffer/NotifLog",null);
        kvMap.put("systemui/tag/NotifBindPipeline",null);
        kvMap.put("systemui/flags/100",null);
        kvMap.put("systemui/flags/402",null);
        kvMap.put("lock_screen_show_silent_notifications",null);
        kvMap.put("hide_rotation_lock_toggle_for_accessibility",random.next0or1());
        kvMap.put("accelerometer_rotation_angles",null);
        kvMap.put("show_temperature_warning",null);
        kvMap.put("show_usb_temperature_alarm",null);
        kvMap.put("sysui_force_enable_leak_reporting",null);
        kvMap.put("systemui/flags/800",null);
        kvMap.put("lock_screen_show_notifications","1");
        kvMap.put("systemui/tag/NotificationEntryMgr",null);
        kvMap.put("systemui/buffer/NotifSectionLog",null);
        kvMap.put("systemui/tag/NotifSections",null);
        kvMap.put("sysui_rounded_size",null);
        kvMap.put("sysui_nav_bar_inverse",null);
        kvMap.put("user_switcher_enabled","0");
        kvMap.put("sysui_keyguard_right",null);
        kvMap.put("sysui_keyguard_left",null);
        kvMap.put("clock_seconds",null);
        kvMap.put("lock_screen_custom_clock_face",null);
        kvMap.put("lockscreen_use_double_line_clock",null);
        kvMap.put("keyguard_slice_uri",null);
        kvMap.put("tether_supported",null);
        kvMap.put("subscription_mode",random.next0or1());
        kvMap.put("enable_radio_bug_detection",null);
        kvMap.put("radio_bug_wakelock_timeout_count_threshold",null);
        kvMap.put("radio_bug_system_error_count_threshold",null);
        kvMap.put("settings_support_large_screen",null);
        kvMap.put("force_resizable_activities","0");
        kvMap.put("show_angle_in_use_dialog_box",null);
        String temp = String.valueOf(random.nextInt(5)+1);
        kvMap.put("multi_sim_voice_call",temp);
        kvMap.put("multi_sim_sms",temp);
        kvMap.put("multi_sim_data_call",temp);
        kvMap.put("telecom.stale_session_cleanup_timeout_millis",null);
        kvMap.put("volte_vt_enabled",null);
        kvMap.put("vt_ims_enabled",null);
        kvMap.put("wfc_ims_enabled",null);
        kvMap.put("wfc_ims_mode",null);
        kvMap.put("wfc_ims_roaming_mode",null);
        kvMap.put("wfc_ims_roaming_enabled",null);
        kvMap.put("status_bar_show_vibrate_icon",null);
        kvMap.put("telecom.call_recording_tone_repeat_interval",null);
        kvMap.put("sms_outgoing_check_max_count",null);
        kvMap.put("systemui/buffer/CollapsedSbFragmentLog",null);
        kvMap.put("sms_outgoing_check_interval_ms",null);
        kvMap.put("systemui/tag/CollapsedSbFragment",null);
        kvMap.put("sms_short_code_confirmation",null);
        kvMap.put("preferred_tty_mode",null);
        kvMap.put("sysui_qs_tiles","internet,bt,flashlight,dnd,alarm,airplane,controls,rotation,battery,cast,screenrecord,mictoggle,cameratoggle,dark,saver,hotspot,work");
        kvMap.put("systemui/buffer/QSLog",null);
        kvMap.put("systemui/tag/QSLog",null);
        kvMap.put("sms_short_code_rule",null);
        kvMap.put("zen_duration","0");
        kvMap.put("low_power_warning_acknowledged",random.next0or1());
        kvMap.put("qs_auto_tiles","cast,work,saver,hotspot");
        kvMap.put("controls_enabled",null);
        kvMap.put("development_settings_enabled","0");
        kvMap.put("enable_cellular_on_boot",random.next0or1());
        kvMap.put("mobile_data",random.next0or1());
        kvMap.put("systemui/flags/300",null);
        kvMap.put("sysui_pm_lite",null);
        kvMap.put("qs_less_rows",null);
        kvMap.put("qs_show_brightness",null);
        kvMap.put("systemui/buffer/PrivacyLog",null);
        kvMap.put("systemui/tag/PrivacyLog",null);
        kvMap.put("sysui_qs_fancy_anim",null);
        kvMap.put("sysui_qs_move_whole_rows",null);
        kvMap.put("systemui/buffer/QSFragmentDisableFlagsLog",null);
        kvMap.put("systemui/tag/QSFragmentDisableFlagsLog",null);
        kvMap.put("systemui/tag/NotCurrentUserFilter",null);
        kvMap.put("systemui/tag/ShadeListBuilder",null);
        kvMap.put("theme_customization_overlay_packages","{\"android.theme.customization.color_both\":\"1\",\"android.theme.customization.color_source\":\"home_wallpaper\",\"_applied_timestamp\":"+String.valueOf(Math.min(Math.max(random.nextLong(),1717751189 + random.nextInt(1000000)),System.currentTimeMillis() - 10000))+"}");
        kvMap.put("systemui/flags/202",null);
        kvMap.put("systemui/flags/401",null);
        kvMap.put("enable_fullscreen_user_switcher",null);
        kvMap.put("lock_screen_allow_private_notifications",random.next0or1());
        kvMap.put("use_blast_adapter_sv",null);
        kvMap.put("show_password",null);
        kvMap.put("force_emergency_affordance",null);
        kvMap.put("emergency_affordance_needed",null);
        kvMap.put("cell_on","1");
        kvMap.put("hearing_aid",random.next0or1());
        kvMap.put("binder_calls_stats",null);
        kvMap.put("data_roaming",random.next0or1());
        kvMap.put("systemui/tag/NotifCollection",null);
        kvMap.put("systemui/tag/RowContentBindStage",null);
        kvMap.put("show_notification_snooze",null);
        kvMap.put("notification_bubbles",random.next0or1());
        kvMap.put("mobile_data5",random.next0or1());

        kvMap.put("doze_enabled",null);
        kvMap.put("bluetooth_voip_state",null);
        kvMap.put("screen_off_timeout",String.valueOf(Consts.SCREEN_OFF_TIMEOUT_ARR[random.nextInt(Consts.SCREEN_OFF_TIMEOUT_ARR.length)]));
        kvMap.put("wifi_sleep_policy",String.valueOf(random.nextInt(3)));
        kvMap.put("default_input_method","com.sohu.inputmethod.sogou/com.sohu.inputmethod.sogou.SogouIME");
        kvMap.put("selected_search_engine",null);
        kvMap.put("mock_location","0");
        kvMap.put("89884a87498ef44f",null);
        kvMap.put("font_weight_adjustment",null);
        kvMap.put("com.q.zi.i",null);
        kvMap.put("bd_setting_i",null);
        kvMap.put("com.baidu.deviceid",null);
        kvMap.put("com.baidu.deviceid.v2",null);
        kvMap.put("DED0AFDB1AD0CC4CA974D5EBA0165141",null);
        kvMap.put("accessibility_captioning_font_scale",null);
        kvMap.put("accessibility_captioning_preset",null);
        kvMap.put("simple_mode_enabled",null);
        kvMap.put("new_simple_mode",null);
        kvMap.put("bluetooth_address",null);
        kvMap.put("system_locales","zh-CN");
        kvMap.put("speak_password","1");
        kvMap.put("alarm_alert",random.next0or1());
        kvMap.put("bluetooth_name",random.nextString(random.nextInt(10)+3));
        kvMap.put("adb_wifi_enabled","0");
        kvMap.put("peak_refresh_rate","0");
        kvMap.put("ringtone",random.next0or1());
        kvMap.put("volume_alarm_speaker",String.valueOf(random.nextInt(255)));
        kvMap.put("volume_ring_speaker",String.valueOf(random.nextInt(255)));
        kvMap.put("volume_voice_earpiece",String.valueOf(random.nextInt(255)));
        kvMap.put("volume_music_speaker",String.valueOf(random.nextInt(255)));
        kvMap.put("require_password_to_decrypt",String.valueOf(random.nextInt(255)));
        kvMap.put("display_color_mode",String.valueOf(random.nextInt(255)));
        kvMap.put("average_time_to_discharge",String.valueOf(random.nextInt(255)));
        kvMap.put("volume_voice",random.next0or1());
        kvMap.put("volume_system",random.next0or1());
        kvMap.put("volume_ring",random.next0or1());
        kvMap.put("volume_music",random.next0or1());
        kvMap.put("volume_bluetooth_sco",random.next0or1());
        kvMap.put("volume_alarm",random.next0or1());
        kvMap.put("mobile_data_always_on",random.next0or1());
        kvMap.put("night_display_forced_auto_mode_available",random.next0or1());
        kvMap.put("verifier_verify_adb_installs","1");
        kvMap.put("wifi_connected_mac_randomization_enabled",random.next0or1());
        kvMap.put("default_customed_apk",random.next0or1());
        kvMap.put("vibrate_when_ringing",random.next0or1());
        kvMap.put("date_format",random.next0or1());
        kvMap.put("stay_on_while_plugged_in",random.next0or1());
        kvMap.put("mode_ringer",random.next0or1());
        kvMap.put("bluetooth_discoverability",random.next0or1());
        kvMap.put("auto_time_zone",random.next0or1());
        kvMap.put("auto_time",random.next0or1());
        kvMap.put("dark_mode_enable",random.next0or1());
        kvMap.put("next_alarm_formatted",random.next0or1());
        kvMap.put("accessibility_enabled","0");
        kvMap.put("7934039a7252be16",null);

    }
}
